{
 "title": "My diploma app monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Diploma application is working",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"my-diploma-service.default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"my-diploma-service.default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"diploma-http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Returned content length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "probe_http_content_length{instance=\"my-diploma-service.default\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}